/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AiType = 'OPEN_AI_CUSTOM' | 'OPEN_AI' | 'GEMINI';

export const AiType = {
    OpenAiCustom: 'OPEN_AI_CUSTOM' as AiType,
    OpenAi: 'OPEN_AI' as AiType,
    Gemini: 'GEMINI' as AiType
};

