/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Scope/permissions for API keys
 */
export type ApiKeyScope = 'r' | 'w' | 'rw';

export const ApiKeyScope = {
    R: 'r' as ApiKeyScope,
    W: 'w' as ApiKeyScope,
    Rw: 'rw' as ApiKeyScope
};

