/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AssociatedEntityType = 'SYSTEM_EMAIL' | 'RECEIPT_PROCESSING_SETTINGS';

export const AssociatedEntityType = {
    SystemEmail: 'SYSTEM_EMAIL' as AssociatedEntityType,
    ReceiptProcessingSettings: 'RECEIPT_PROCESSING_SETTINGS' as AssociatedEntityType
};

