/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulkStatusUpdateCommand { 
    /**
     * Optional comment to leave on each receipt
     */
    comment?: string;
    /**
     * Status to update to
     */
    status: string;
    /**
     * Receipt ids to update
     */
    receiptIds: Array<number>;
}

