/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface Claims { 
    /**
     * User foreign key
     */
    userId: number;
    userRole: UserRole;
    /**
     * Display name
     */
    displayName: string;
    /**
     * Default avatar color
     */
    defaultAvatarColor: string;
    /**
     * User\'s username used to login
     */
    username: string;
    /**
     * Issuer
     */
    iss: string;
    /**
     * Subject
     */
    sub?: string;
    /**
     * Audience
     */
    aud?: Array<string>;
    /**
     * Expiration time
     */
    exp: number;
    /**
     * Not before
     */
    nbf?: number;
    /**
     * Issued at
     */
    iat?: number;
    /**
     * JWT ID
     */
    jti?: string;
}

