/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomFieldValue { 
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    /**
     * Receipt Id
     */
    receiptId: number;
    /**
     * Custom Field ID
     */
    customFieldId: number;
    /**
     * Custom Field Value
     */
    value?: string;
}

