/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeatureConfig { 
    /**
     * Whether AI powered receipts are enabled
     */
    aiPoweredReceipts: boolean;
    /**
     * Whether local sign up is enabled
     */
    enableLocalSignUp: boolean;
}

