/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sortDirection';
import { AssociatedEntityType } from './associatedEntityType';


export interface GetSystemTaskCommand { 
    /**
     * Associated entity id
     */
    associatedEntityId?: number;
    associatedEntityType?: AssociatedEntityType;
    /**
     * Page number
     */
    page: number;
    /**
     * Number of records per page
     */
    pageSize: number;
    /**
     * field to order on
     */
    orderBy?: string;
    sortDirection?: SortDirection;
}
export namespace GetSystemTaskCommand {
}


