/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OcrEngine = 'TESSERACT' | 'EASY_OCR';

export const OcrEngine = {
    Tesseract: 'TESSERACT' as OcrEngine,
    EasyOcr: 'EASY_OCR' as OcrEngine
};

