/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Item } from './item';
import { Category } from './category';
import { Receipt } from './receipt';
import { ReceiptStatus } from './receiptStatus';
import { Tag } from './tag';
import { FileData } from './fileData';


export interface PagedDataDataInner { 
    /**
     * Receipt total amount
     */
    amount: string;
    /**
     * Categories associated to receipt
     */
    categories?: Array<Category>;
    /**
     * Comments associated to receipt
     */
    comments?: Array<Comment>;
    createdAt?: string;
    createdBy?: number;
    /**
     * Receipt date
     */
    date: string;
    /**
     * Group foreign key
     */
    groupId: number;
    id: number;
    /**
     * Files associated to receipt
     */
    imageFiles?: Array<FileData>;
    /**
     * Tag name
     */
    name: string;
    /**
     * User paid foreign key
     */
    paidByUserId: number;
    /**
     * Items associated to receipt
     */
    receiptItems?: Array<Item>;
    /**
     * Date resolved
     */
    resolvedDate?: string;
    status: ReceiptStatus;
    /**
     * Tags associated to receipt
     */
    tags?: Array<Tag>;
    updatedAt?: string;
    /**
     * Created by string, which is anything that is not a user
     */
    createdByString?: string;
    /**
     * Tag description
     */
    description?: string;
}
export namespace PagedDataDataInner {
}


