/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedDataDataInner } from './pagedDataDataInner';


export interface PagedData { 
    data: Array<PagedDataDataInner>;
    totalCount: number;
}

