/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OcrEngine } from './ocrEngine';
import { AiType } from './aiType';


export interface ReceiptProcessingSettingsAllOf { 
    aiType?: AiType;
    /**
     * URL for custom endpoints
     */
    url?: string;
    /**
     * Key for endpoints that require authentication
     */
    key?: string;
    /**
     * LLM model
     */
    model?: string;
    /**
     * Number of workers to use
     */
    numWorkers?: number;
    ocrEngine?: OcrEngine;
    /**
     * Whether these settings are enabled or not
     */
    enabled?: boolean;
}

