/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { ShareStatus } from './shareStatus';
import { Tag } from './tag';


/**
 * Share on a receipt
 */
export interface Share { 
    /**
     * Is taxed (not used)
     */
    IsTaxed?: boolean;
    /**
     * Amount the share costs
     */
    amount: string;
    /**
     * User foreign key
     */
    chargedToUserId: number;
    createdAt?: string;
    createdBy?: number;
    id?: number;
    /**
     * Share name
     */
    name: string;
    /**
     * Receipt foreign key
     */
    receiptId: number;
    status: ShareStatus;
    /**
     * Categories associated to the share
     */
    categories?: Array<Category>;
    /**
     * Tags associated to the share
     */
    tags?: Array<Tag>;
    updatedAt?: string;
}
export namespace Share {
}


