/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface SignUpCommand { 
    /**
     * User\'s username
     */
    username: string;
    /**
     * User\'s password
     */
    password: string;
    /**
     * User\'s displayname
     */
    displayName?: string;
    /**
     * Whether the user is a dummy user
     */
    isDummyUser?: boolean;
    /**
     * User\'s role
     */
    userRole?: UserRole;
}
export namespace SignUpCommand {
}


