/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemTaskStatus } from './systemTaskStatus';
import { SystemTaskType } from './systemTaskType';
import { AssociatedEntityType } from './associatedEntityType';


export interface SystemTask { 
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    type?: SystemTaskType;
    status?: SystemTaskStatus;
    startedAt?: string;
    endedAt?: string;
    associatedEntityId?: number;
    associatedEntityType?: AssociatedEntityType;
    ranByUserId?: number;
    resultDescription?: string;
    childSystemTasks?: Array<SystemTask>;
    asynqTaskId?: string;
}
export namespace SystemTask {
}


