/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencySeparator } from './currencySeparator';
import { CurrencySymbolPosition } from './currencySymbolPosition';


export interface SystemSettings { 
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    /**
     * Whether local sign up is enabled
     */
    enableLocalSignUp?: boolean;
    /**
     * Currency display
     */
    currencyDisplay?: string;
    currencyThousandthsSeparator?: CurrencySeparator;
    currencyDecimalSeparator?: CurrencySeparator;
    currencySymbolPosition?: CurrencySymbolPosition;
    /**
     * Whether to hide decimal places
     */
    currencyHideDecimalPlaces?: boolean;
    /**
     * Debug OCR
     */
    debugOcr?: boolean;
    /**
     * Number of workers to use
     */
    numWorkers?: number;
    /**
     * Email polling interval
     */
    emailPollingInterval?: number;
    /**
     * Receipt processing settings foreign key
     */
    receiptProcessingSettingsId?: number;
    /**
     * Fallback receipt processing settings foreign key
     */
    fallbackReceiptProcessingSettingsId?: number;
}
export namespace SystemSettings {
}


