/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectLineRegex } from './subjectLineRegex';
import { ReceiptStatus } from './receiptStatus';
import { GroupSettingsWhiteListEmail } from './groupSettingsWhiteListEmail';


export interface UpdateGroupSettingsCommand { 
    /**
     * System email foreign key
     */
    systemEmailId: number;
    /**
     * Whether email integration is enabled
     */
    emailIntegrationEnabled?: boolean;
    /**
     * Subject line regexes
     */
    subjectLineRegexes: Array<SubjectLineRegex>;
    /**
     * Email white list
     */
    emailWhiteList: Array<GroupSettingsWhiteListEmail>;
    /**
     * Default receipt status
     */
    emailDefaultReceiptStatus?: ReceiptStatus;
    /**
     * User foreign key
     */
    emailDefaultReceiptPaidById?: number;
    /**
     * Prompt foreign key
     */
    promptId?: number;
    /**
     * Fallback prompt foreign key
     */
    fallbackPromptId?: number;
}
export namespace UpdateGroupSettingsCommand {
}


