/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpsertCategoryCommand } from './upsertCategoryCommand';
import { ShareStatus } from './shareStatus';
import { UpsertTagCommand } from './upsertTagCommand';


export interface UpsertShareCommand { 
    /**
     * Amount the share costs
     */
    amount: string;
    /**
     * User foreign key
     */
    chargedToUserId: number;
    /**
     * Share name
     */
    name: string;
    /**
     * Receipt foreign key
     */
    receiptId: number;
    status: ShareStatus;
    /**
     * Categories associated to share
     */
    categories?: Array<UpsertCategoryCommand>;
    /**
     * Tags associated to share
     */
    tags?: Array<UpsertTagCommand>;
}
export namespace UpsertShareCommand {
}


