/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertSystemSettingsCommand { 
    /**
     * Whether local sign up is enabled
     */
    enableLocalSignUp?: boolean;
    /**
     * Currency display
     */
    currencyDisplay?: string;
    /**
     * Currency locale
     */
    currencyLocale?: string;
    /**
     * Currency code
     */
    currencyCode?: string;
    /**
     * Show currency symbol
     */
    showCurrencySymbol?: boolean;
    debugOcr?: boolean;
    /**
     * Number of workers to use
     */
    numWorkers?: number;
    /**
     * Email polling interval
     */
    emailPollingInterval?: number;
    /**
     * Receipt processing settings foreign key
     */
    receiptProcessingSettingsId?: number;
    /**
     * Fallback receipt processing settings foreign key
     */
    fallbackReceiptProcessingSettingsId?: number;
}

