/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertSystemEmailCommand { 
    /**
     * IMAP host
     */
    host: string;
    /**
     * IMAP port
     */
    port: number;
    /**
     * IMAP username
     */
    username: string;
    /**
     * IMAP password
     */
    password: string;
}

