/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptStatus } from './receiptStatus';
import { UserShortcut } from './userShortcut';


export interface UserPreferences { 
    /**
     * User preferences id
     */
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    /**
     * User foreign key
     */
    userId: number;
    /**
     * Group foreign key
     */
    quickScanDefaultGroupId?: number;
    /**
     * User foreign key
     */
    quickScanDefaultPaidById?: number;
    /**
     * Default quick scan status
     */
    quickScanDefaultStatus?: ReceiptStatus;
    /**
     * Whether to show large image previews
     */
    showLargeImagePreviews?: boolean;
    userShortcuts?: Array<UserShortcut>;
}
export namespace UserPreferences {
}


