/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WidgetType = 'GROUP_SUMMARY' | 'FILTERED_RECEIPTS';

export const WidgetType = {
    GroupSummary: 'GROUP_SUMMARY' as WidgetType,
    FilteredReceipts: 'FILTERED_RECEIPTS' as WidgetType
};

