/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WidgetType = 'GROUP_SUMMARY' | 'FILTERED_RECEIPTS';

export const WidgetType = {
    GroupSummary: 'GROUP_SUMMARY' as WidgetType,
    FilteredReceipts: 'FILTERED_RECEIPTS' as WidgetType
};

