# Build app
FROM arm64v8/node:lts-alpine3.17 as node
WORKDIR .
RUN mkdir desktop
WORKDIR desktop
COPY . .
# Uncomment this for local development
#COPY qemu-arm-static /usr/bin/qemu-arm-static
RUN npm i -g @angular/cli@15.0.4
RUN npm i
RUN ng build

# Deploy via nginx
FROM arm64v8/nginx:alpine
COPY --from=node /desktop/dist/receipt-wrangler /usr/share/nginx/html
COPY --from=node /desktop/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
