/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * File data for images on a receipt
 */
export interface FileData { 
    createdAt?: Date;
    createdBy?: number;
    /**
     * MIME file type
     */
    fileType?: string;
    id?: number;
    /**
     * Image data
     */
    imageData: Array<number>;
    /**
     * File name
     */
    name?: string;
    /**
     * Receipt foreign key
     */
    receiptId: number;
    /**
     * File size
     */
    size?: number;
    updatedAt?: Date;
}