import { Component, Input } from "@angular/core";
import { FormControl } from "@angular/forms";
import { FormOption } from "../../interfaces/form-option.interface";

@Component({
  selector: "app-icon-autocomplete",
  templateUrl: "./icon-autocomplete.component.html",
  styleUrl: "./icon-autocomplete.component.scss"
})
export class IconAutocompleteComponent {
  @Input() public inputFormControl!: FormControl;

  @Input() public label = "";

  public readonly icons: FormOption[] = [
    { value: "search", displayValue: "Search" },
    { value: "home", displayValue: "Home" },
    { value: "menu", displayValue: "Menu" },
    { value: "close", displayValue: "Close" },
    { value: "settings", displayValue: "Settings" },
    { value: "check_circle", displayValue: "Check Circle" },
    { value: "favorite", displayValue: "Favorite" },
    { value: "add", displayValue: "Add" },
    { value: "delete", displayValue: "Delete" },
    { value: "arrow_back", displayValue: "Arrow Back" },
    { value: "star", displayValue: "Star" },
    { value: "chevron_right", displayValue: "Chevron Right" },
    { value: "logout", displayValue: "Logout" },
    { value: "arrow_forward_ios", displayValue: "Arrow Forward iOS" },
    { value: "add_circle", displayValue: "Add Circle" },
    { value: "cancel", displayValue: "Cancel" },
    { value: "arrow_back_ios", displayValue: "Arrow Back iOS" },
    { value: "arrow_forward", displayValue: "Arrow Forward" },
    { value: "arrow_drop_down", displayValue: "Arrow Drop Down" },
    { value: "more_vert", displayValue: "More Vertical" },
    { value: "check", displayValue: "Check" },
    { value: "check_box", displayValue: "Check Box" },
    { value: "open_in_new", displayValue: "Open in New" },
    { value: "toggle_on", displayValue: "Toggle On" },
    { value: "grade", displayValue: "Grade" },
    { value: "refresh", displayValue: "Refresh" },
    { value: "check_box_outline_blank", displayValue: "Check Box Outline Blank" },
    { value: "login", displayValue: "Login" },
    { value: "chevron_left", displayValue: "Chevron Left" },
    { value: "radio_button_unchecked", displayValue: "Radio Button Unchecked" },
    { value: "more_horiz", displayValue: "More Horizontal" },
    { value: "download", displayValue: "Download" },
    { value: "apps", displayValue: "Apps" },
    { value: "arrow_right_alt", displayValue: "Arrow Right Alt" },
    { value: "radio_button_checked", displayValue: "Radio Button Checked" },
    { value: "remove", displayValue: "Remove" },
    { value: "bolt", displayValue: "Bolt" },
    { value: "arrow_upward", displayValue: "Arrow Upward" },
    { value: "toggle_off", displayValue: "Toggle Off" },
    { value: "filter_list", displayValue: "Filter List" },
    { value: "delete_forever", displayValue: "Delete Forever" },
    { value: "autorenew", displayValue: "Auto Renew" },
    { value: "key", displayValue: "Key" },
    { value: "block", displayValue: "Block" },
    { value: "sync", displayValue: "Sync" },
    { value: "arrow_downward", displayValue: "Arrow Downward" },
    { value: "sort", displayValue: "Sort" },
    { value: "add_box", displayValue: "Add Box" },
    { value: "arrow_back_ios_new", displayValue: "Arrow Back iOS New" },
    { value: "restart_alt", displayValue: "Restart Alt" },
    { value: "shopping_cart_checkout", displayValue: "Shopping Cart Checkout" },
    { value: "menu_open", displayValue: "Menu Open" },
    { value: "expand_circle_down", displayValue: "Expand Circle Down" },
    { value: "undo", displayValue: "Undo" },
    { value: "backspace", displayValue: "Backspace" },
    { value: "arrow_circle_right", displayValue: "Arrow Circle Right" },
    { value: "done_all", displayValue: "Done All" },
    { value: "arrow_right", displayValue: "Arrow Right" },
    { value: "do_not_disturb_on", displayValue: "Do Not Disturb On" },
    { value: "open_in_full", displayValue: "Open in Full" },
    { value: "manage_search", displayValue: "Manage Search" },
    { value: "double_arrow", displayValue: "Double Arrow" },
    { value: "sync_alt", displayValue: "Sync Alt" },
    { value: "done_outline", displayValue: "Done Outline" },
    { value: "zoom_in", displayValue: "Zoom In" },
    { value: "drag_indicator", displayValue: "Drag Indicator" },
    { value: "fullscreen", displayValue: "Fullscreen" },
    { value: "keyboard_double_arrow_right", displayValue: "Keyboard Double Arrow Right" },
    { value: "star_half", displayValue: "Star Half" },
    { value: "ios_share", displayValue: "iOS Share" },
    { value: "settings_accessibility", displayValue: "Settings Accessibility" },
    { value: "arrow_drop_up", displayValue: "Arrow Drop Up" },
    { value: "reply", displayValue: "Reply" },
    { value: "exit_to_app", displayValue: "Exit to App" },
    { value: "unfold_more", displayValue: "Unfold More" },
    { value: "library_add", displayValue: "Library Add" },
    { value: "cached", displayValue: "Cached" },
    { value: "terminal", displayValue: "Terminal" },
    { value: "select_check_box", displayValue: "Select Check Box" },
    { value: "change_circle", displayValue: "Change Circle" },
    { value: "disabled_by_default", displayValue: "Disabled by Default" },
    { value: "swap_horiz", displayValue: "Swap Horizontal" },
    { value: "swap_vert", displayValue: "Swap Vertical" },
    { value: "close_fullscreen", displayValue: "Close Fullscreen" },
    { value: "app_registration", displayValue: "App Registration" },
    { value: "download_for_offline", displayValue: "Download for Offline" },
    { value: "arrow_circle_up", displayValue: "Arrow Circle Up" },
    { value: "dataset", displayValue: "Dataset" },
    { value: "arrow_circle_left", displayValue: "Arrow Circle Left" },
    { value: "minimize", displayValue: "Minimize" },
    { value: "file_open", displayValue: "File Open" },
    { value: "open_with", displayValue: "Open With" },
    { value: "add_task", displayValue: "Add Task" },
    { value: "keyboard_double_arrow_left", displayValue: "Keyboard Double Arrow Left" },
    { value: "start", displayValue: "Start" },
    { value: "keyboard_double_arrow_down", displayValue: "Keyboard Double Arrow Down" },
    { value: "create_new_folder", displayValue: "Create New Folder" },
    { value: "upload", displayValue: "Upload" },
    { value: "forward", displayValue: "Forward" },
    { value: "downloading", displayValue: "Downloading" },
    { value: "compare_arrows", displayValue: "Compare Arrows" },
    { value: "settings_applications", displayValue: "Settings Applications" },
    { value: "redo", displayValue: "Redo" },
    { value: "publish", displayValue: "Publish" },
    { value: "zoom_out", displayValue: "Zoom Out" },
    { value: "arrow_left", displayValue: "Arrow Left" },
    { value: "token", displayValue: "Token" },
    { value: "html", displayValue: "HTML" },
    { value: "switch_access_shortcut", displayValue: "Switch Access Shortcut" },
    { value: "fullscreen_exit", displayValue: "Fullscreen Exit" },
    { value: "arrow_circle_down", displayValue: "Arrow Circle Down" },
    { value: "sort_by_alpha", displayValue: "Sort by Alpha" },
    { value: "delete_sweep", displayValue: "Delete Sweep" },
    { value: "indeterminate_check_box", displayValue: "Indeterminate Check Box" },
    { value: "first_page", displayValue: "First Page" },
    { value: "view_timeline", displayValue: "View Timeline" },
    { value: "keyboard_double_arrow_up", displayValue: "Keyboard Double Arrow Up" },
    { value: "settings_backup_restore", displayValue: "Settings Backup Restore" },
    { value: "sync_problem", displayValue: "Sync Problem" },
    { value: "assistant_navigation", displayValue: "Assistant Navigation" },
    { value: "arrow_drop_down_circle", displayValue: "Arrow Drop Down Circle" },
    { value: "heart_plus", displayValue: "Heart Plus" },
    { value: "clear_all", displayValue: "Clear All" },
    { value: "density_medium", displayValue: "Density Medium" },
    { value: "expand", displayValue: "Expand" },
    { value: "subdirectory_arrow_right", displayValue: "Subdirectory Arrow Right" },
    { value: "filter_alt_off", displayValue: "Filter Alt Off" },
    { value: "arrow_outward", displayValue: "Arrow Outward" },
    { value: "last_page", displayValue: "Last Page" },
    { value: "unfold_less", displayValue: "Unfold Less" },
    { value: "download_done", displayValue: "Download Done" },
    { value: "swipe_left", displayValue: "Swipe Left" },
    { value: "saved_search", displayValue: "Saved Search" },
    { value: "system_update_alt", displayValue: "System Update Alt" },
    { value: "output", displayValue: "Output" },
    { value: "place_item", displayValue: "Place Item" },
    { value: "search_off", displayValue: "Search Off" },
    { value: "javascript", displayValue: "JavaScript" },
    { value: "maximize", displayValue: "Maximize" },
    { value: "swipe_up", displayValue: "Swipe Up" },
    { value: "select_all", displayValue: "Select All" },
    { value: "fit_screen", displayValue: "Fit Screen" },
    { value: "hide_source", displayValue: "Hide Source" },
    { value: "check_small", displayValue: "Check Small" },
    { value: "dynamic_form", displayValue: "Dynamic Form" },
    { value: "swipe_right", displayValue: "Swipe Right" },
    { value: "browse_gallery", displayValue: "Browse Gallery" },
    { value: "switch_access_shortcut_add", displayValue: "Switch Access Shortcut Add" },
    { value: "density_small", displayValue: "Density Small" },
    { value: "css", displayValue: "CSS" },
    { value: "assistant_direction", displayValue: "Assistant Direction" },
    { value: "move_up", displayValue: "Move Up" },
    { value: "youtube_searched_for", displayValue: "YouTube Searched For" },
    { value: "data_thresholding", displayValue: "Data Thresholding" },
    { value: "swap_horizontal_circle", displayValue: "Swap Horizontal Circle" },
    { value: "install_mobile", displayValue: "Install Mobile" },
    { value: "abc", displayValue: "ABC" },
    { value: "move_down", displayValue: "Move Down" },
    { value: "dataset_linked", displayValue: "Dataset Linked" },
    { value: "restore_from_trash", displayValue: "Restore from Trash" },
    { value: "enable", displayValue: "Enable" },
    { value: "browse_activity", displayValue: "Browse Activity" },
    { value: "install_desktop", displayValue: "Install Desktop" },
    { value: "keyboard_command_key", displayValue: "Keyboard Command Key" },
    { value: "view_kanban", displayValue: "View Kanban" },
    { value: "reply_all", displayValue: "Reply All" },
    { value: "switch_left", displayValue: "Switch Left" },
    { value: "compress", displayValue: "Compress" },
    { value: "swipe_down", displayValue: "Swipe Down" },
    { value: "star_rate", displayValue: "Star Rate" },
    { value: "apps_outage", displayValue: "Apps Outage" },
    { value: "swap_vertical_circle", displayValue: "Swap Vertical Circle" },
    { value: "remove_done", displayValue: "Remove Done" },
    { value: "filter_list_off", displayValue: "Filter List Off" },
    { value: "hide", displayValue: "Hide" },
    { value: "sync_disabled", displayValue: "Sync Disabled" },
    { value: "swipe_vertical", displayValue: "Swipe Vertical" },
    { value: "switch_right", displayValue: "Switch Right" },
    { value: "more_up", displayValue: "More Up" },
    { value: "pinch", displayValue: "Pinch" },
    { value: "keyboard_control_key", displayValue: "Keyboard Control Key" },
    { value: "tab", displayValue: "Tab" },
    { value: "eject", displayValue: "Eject" },
    { value: "key_off", displayValue: "Key Off" },
    { value: "php", displayValue: "PHP" },
    { value: "subdirectory_arrow_left", displayValue: "Subdirectory Arrow Left" },
    { value: "view_cozy", displayValue: "View Cozy" },
    { value: "transcribe", displayValue: "Transcribe" },
    { value: "do_not_disturb_off", displayValue: "Do Not Disturb Off" },
    { value: "send_time_extension", displayValue: "Send Time Extension" },
    { value: "width_normal", displayValue: "Width Normal" },
    { value: "view_comfy_alt", displayValue: "View Comfy Alt" },
    { value: "heart_minus", displayValue: "Heart Minus" },
    { value: "share_reviews", displayValue: "Share Reviews" },
    { value: "width_full", displayValue: "Width Full" },
    { value: "file_download_off", displayValue: "File Download Off" },
    { value: "unfold_more_double", displayValue: "Unfold More Double" },
    { value: "view_compact_alt", displayValue: "View Compact Alt" },
    { value: "progress_activity", displayValue: "Progress Activity" },
    { value: "extension_off", displayValue: "Extension Off" },
    { value: "cycle", displayValue: "Cycle" },
    { value: "open_in_new_off", displayValue: "Open in New Off" },
    { value: "check_indeterminate_small", displayValue: "Check Indeterminate Small" },
    { value: "more_down", displayValue: "More Down" },
    { value: "width_wide", displayValue: "Width Wide" },
    { value: "repartition", displayValue: "Repartition" },
    { value: "density_large", displayValue: "Density Large" },
    { value: "swipe_left_alt", displayValue: "Swipe Left Alt" },
    { value: "swipe_down_alt", displayValue: "Swipe Down Alt" },
    { value: "swipe_right_alt", displayValue: "Swipe Right Alt" },
    { value: "swipe_up_alt", displayValue: "Swipe Up Alt" },
    { value: "unfold_less_double", displayValue: "Unfold Less Double" },
    { value: "keyboard_option_key", displayValue: "Keyboard Option Key" },
    { value: "expand_content", displayValue: "Expand Content" },
    { value: "tab_unselected", displayValue: "Tab Unselected" },
    { value: "hls", displayValue: "HLS" },
    { value: "hls_off", displayValue: "HLS Off" },
    { value: "file_upload_off", displayValue: "File Upload Off" },
    { value: "rebase", displayValue: "Rebase" },
    { value: "expand_all", displayValue: "Expand All" },
    { value: "deployed_code", displayValue: "Deployed Code" },
    { value: "quick_reference_all", displayValue: "Quick Reference All" },
    { value: "collapse_all", displayValue: "Collapse All" },
    { value: "rebase_edit", displayValue: "Rebase Edit" },
    { value: "arrow_split", displayValue: "Arrow Split" },
    { value: "stat_0", displayValue: "Stat 0" },
    { value: "stack", displayValue: "Stack" },
    { value: "acute", displayValue: "Acute" },
    { value: "empty_dashboard", displayValue: "Empty Dashboard" },
    { value: "data_check", displayValue: "Data Check" },
    { value: "arrow_upward_alt", displayValue: "Arrow Upward Alt" },
    { value: "page_info", displayValue: "Page Info" },
    { value: "prompt_suggestion", displayValue: "Prompt Suggestion" },
    { value: "left_click", displayValue: "Left Click" },
    { value: "quick_reference", displayValue: "Quick Reference" },
    { value: "sync_saved_locally", displayValue: "Sync Saved Locally" },
    { value: "clock_loader_60", displayValue: "Clock Loader 60" },
    { value: "switches", displayValue: "Switches" },
    { value: "stacks", displayValue: "Stacks" },
    { value: "data_alert", displayValue: "Data Alert" },
    { value: "arrow_insert", displayValue: "Arrow Insert" },
    { value: "collapse_content", displayValue: "Collapse Content" },
    { value: "arrow_downward_alt", displayValue: "Arrow Downward Alt" },
    { value: "captive_portal", displayValue: "Captive Portal" },
    { value: "point_scan", displayValue: "Point Scan" },
    { value: "directory_sync", displayValue: "Directory Sync" },
    { value: "search_check", displayValue: "Search Check" },
    { value: "rule_settings", displayValue: "Rule Settings" },
    { value: "unknown_med", displayValue: "Unknown Med" },
    { value: "question_exchange", displayValue: "Question Exchange" },
    { value: "clock_loader_10", displayValue: "Clock Loader 10" },
    { value: "data_info_alert", displayValue: "Data Info Alert" },
    { value: "side_navigation", displayValue: "Side Navigation" },
    { value: "step", displayValue: "Step" },
    { value: "cards", displayValue: "Cards" },
    { value: "expand_circle_right", displayValue: "Expand Circle Right" },
    { value: "steppers", displayValue: "Steppers" },
    { value: "stack_star", displayValue: "Stack Star" }
  ];

  public displayWith(value: string): string {
    return this.icons.find((icon) => icon.value === value)?.displayValue ?? "";
  }
}
