/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMember } from './groupMember';
import { GroupStatus } from './groupStatus';
import { GroupSettings } from './groupSettings';


/**
 * Group in the system
 */
export interface Group { 
    createdAt?: string;
    createdBy?: number;
    groupSettings?: GroupSettings;
    /**
     * Members of the group
     */
    groupMembers: Array<GroupMember>;
    id: number;
    /**
     * Is default group (not used yet)
     */
    isDefault?: boolean;
    /**
     * Name of the group
     */
    name: string;
    /**
     * Is all group for user
     */
    isAllGroup: boolean;
    status: GroupStatus;
    updatedAt?: string;
}

