/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Comment } from './comment';
import { FileData } from './fileData';
import { Item } from './item';
import { Tag } from './tag';

/**
 * Receipt
 */
export interface Receipt { 
    /**
     * Reciept total amount
     */
    amount: string;
    /**
     * Categories associated to receipt
     */
    categories?: Array<Category>;
    /**
     * Comments associated to receipt
     */
    comments?: Array<Comment>;
    createdAt?: Date;
    createdBy?: number;
    /**
     * Receipt date
     */
    date: Date;
    /**
     * Group foreign key
     */
    groupId: number;
    id: number;
    /**
     * Files associated to receipt
     */
    imageFiles?: Array<FileData>;
    /**
     * Receipt name
     */
    name: string;
    /**
     * User paid foreign key
     */
    paidByUserId: number;
    /**
     * Items associated to receipt
     */
    receiptItems?: Array<Item>;
    /**
     * Date resolved
     */
    resolvedDate?: Date;
    status: Receipt.StatusEnum;
    /**
     * Tags associated to receipt
     */
    tags?: Array<Tag>;
    updatedAt?: Date;
}
export namespace Receipt {
    export type StatusEnum = 'OPEN' | 'NEEDS_ATTENTION' | 'RESOLVED';
    export const StatusEnum = {
        OPEN: 'OPEN' as StatusEnum,
        NEEDSATTENTION: 'NEEDS_ATTENTION' as StatusEnum,
        RESOLVED: 'RESOLVED' as StatusEnum
    };
}