/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectLineRegex } from './subjectLineRegex';
import { ReceiptStatus } from './receiptStatus';
import { GroupSettingsWhiteListEmail } from './groupSettingsWhiteListEmail';


export interface UpdateGroupSettingsCommand { 
    /**
     * Whether email integration is enabled
     */
    emailIntegrationEnabled?: boolean;
    /**
     * Email to read
     */
    emailToRead: string;
    /**
     * Subject line regexes
     */
    subjectLineRegexes: Array<SubjectLineRegex>;
    /**
     * Email white list
     */
    emailWhiteList: Array<GroupSettingsWhiteListEmail>;
    emailDefaultReceiptStatus?: ReceiptStatus;
    /**
     * User foreign key
     */
    emailDefaultReceiptPaidById?: number;
}

