/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpsertWidgetCommand } from './upsertWidgetCommand';

export interface UpsertDashboardCommand { 
    /**
     * Dashboard name
     */
    name: string;
    /**
     * Group foreign key
     */
    groupId: string;
    /**
     * Widgets associated to dashboard
     */
    widgets?: Array<UpsertWidgetCommand>;
}