/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseModel } from './baseModel';
import { ReceiptStatus } from './receiptStatus';

export interface UserPreferences extends BaseModel { 
    /**
     * User preferences id
     */
    id: number;
    /**
     * User foreign key
     */
    userId: number;
    /**
     * Group foreign key
     */
    quickScanDefaultGroupId?: number;
    /**
     * User foreign key
     */
    quickScanDefaultPaidById?: number;
    quickScanDefaultStatus?: ReceiptStatus;
}