/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';

/**
 * User in the system
 */
export interface User { 
    /**
     * User's password
     */
    password?: string;
    /**
     * User's username used to login
     */
    username: string;
    createdAt?: string;
    createdBy?: number;
    /**
     * Default avatar color
     */
    defaultAvatarColor?: string;
    /**
     * Display name
     */
    displayName: string;
    id: number;
    /**
     * Is dummy user
     */
    isDummyUser: boolean;
    updatedAt?: string;
    userRole: UserRole;
}