/**
 * Receipt Wrangler API.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


/**
 * User in the system
 */
export interface UserView { 
    /**
     * User\'s username used to login
     */
    username: string;
    createdAt?: string;
    createdBy?: number;
    /**
     * Default avatar color
     */
    defaultAvatarColor?: string;
    /**
     * Display name
     */
    displayName: string;
    id: number;
    /**
     * Is dummy user
     */
    isDummyUser: boolean;
    updatedAt?: string;
    userRole: UserRole;
}

