/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * User in the system
 */
export interface UserView { 
    /**
     * User's username used to login
     */
    username: string;
    createdAt?: Date;
    createdBy?: number;
    /**
     * Default avatar color
     */
    defaultAvatarColor?: string;
    /**
     * Display name
     */
    displayName: string;
    id: number;
    /**
     * Is dummy user
     */
    isDummyUser: boolean;
    updatedAt?: Date;
    /**
     * User's role
     */
    userRole: UserView.UserRoleEnum;
}
export namespace UserView {
    export type UserRoleEnum = 'ADMIN' | 'USER';
    export const UserRoleEnum = {
        ADMIN: 'ADMIN' as UserRoleEnum,
        USER: 'USER' as UserRoleEnum
    };
}