name: Angular Tests
on: 
  push:
    branches: ["main"]

jobs:
  build:
    env:
      working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Setup
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: Test
        run: |
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        working-directory: ${{env.working-directory}}
